// <auto-generated />
using System;
using EFCoreTypeHierarchyExample.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTypeHierarchyExample.Common.Migrations
{
    [DbContext(typeof(EFCoreTypeHierarchyExampleContext))]
    partial class EFCoreTypeHierarchyExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreTypeHierarchyExample.Common.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCoreTypeHierarchyExample.Common.Models.Car", b =>
                {
                    b.HasBaseType("EFCoreTypeHierarchyExample.Common.Models.Vehicle");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Car");

                    b.HasData(
                        new
                        {
                            Id = new Guid("960792ad-4442-42cc-84a9-db47832e77c3"),
                            ColorCode = "",
                            Name = "Golf 6",
                            VehicleIdentificationNumber = "IUKDGHFKLSDFSD3123",
                            PassengerCount = 0
                        },
                        new
                        {
                            Id = new Guid("ef950b20-03e3-4c33-ac03-9b0e43a363a3"),
                            ColorCode = "",
                            Name = "Chrysler Fifth Avenue",
                            VehicleIdentificationNumber = "SDFKLDSHGSDFG241",
                            PassengerCount = 0
                        });
                });

            modelBuilder.Entity("EFCoreTypeHierarchyExample.Common.Models.Truck", b =>
                {
                    b.HasBaseType("EFCoreTypeHierarchyExample.Common.Models.Vehicle");

                    b.Property<float>("CargoSpaceSquareMeters")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Truck");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f5120a6-d33b-4cb7-814e-6e86d3f46269"),
                            ColorCode = "",
                            Name = "Mercedes Actros",
                            VehicleIdentificationNumber = "DSKJFGHSDKGDFS231234",
                            CargoSpaceSquareMeters = 0f
                        },
                        new
                        {
                            Id = new Guid("b39f6448-0308-4e59-aee9-5f11e482f2a6"),
                            ColorCode = "",
                            Name = "Iveco Stralis",
                            VehicleIdentificationNumber = "HKLSDFBHDS389423",
                            CargoSpaceSquareMeters = 0f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
